const all__heaphones = [
    {
        id: 1,
        img: 'byzs852i.png',
        title: 'Apple BYZ S852I',
        newPrise: 2927,
        oldPrise: 3527,
        rating: '4.7',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 2,
        img: 'earPods.png',
        title: 'Apple EarPods',
        newPrise: 2327,
        rating: '4.5',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 3,
        img: 'earPods2.png',
        title: 'Apple EarPods',
        newPrise: 2927,
        rating: '4.5',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 4,
        img: 'byzs852i.png',
        title: 'Apple BYZ S852I',
        newPrise: 2927,
        rating: '4.7',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 5,
        img: 'earPods.png',
        title: 'Apple EarPods',
        newPrise: 2327,
        rating: '4.5',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 6,
        img: 'earPods2.png',
        title: 'Apple EarPods',
        newPrise: 2927,
        rating: '4.5',
        count: 0,
        priceTotal: 0,
        type: 'wired',
    },
    {
        id: 7,
        img: 'airPods.png',
        title: 'Apple AirPods',
        newPrise: 9527,
        rating: '4.7',
        count: 0,
        priceTotal: 0,
        type: 'wireless',
    },
    {
        id: 8,
        img: 'gerlax.png',
        title: 'GERLAX GH-04',
        newPrise: 6527,
        rating: '4.7',
        count: 0,
        priceTotal: 0,
        type: 'wireless',
    },
    {
        id: 9,
        img: 'borofone.png',
        title: 'BOROFONE BO4',
        newPrise: 7527,
        rating: '4.7',
        count: 0,
        priceTotal: 0,
        type: 'wireless',
    },
]

export default all__heaphones;